apiVersion: apps/v1
kind: Deployment
metadata:
  name: kios
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: '2022-10-25T04:58:23Z'
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-web-kios
  namespace: web
  resourceVersion: '5989999'
  uid: f8b6bf7c-bbe9-4d3d-8d25-507451c1da0b
  fields:
    - kios
    - 2/2
    - 2
    - 2
    - 24s
    - kios
    - mainamctk33/reactjs:1.0
    - workload.user.cattle.io/workloadselector=apps.deployment-web-kios
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-web-kios
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-web-kios
      creationTimestamp: 
    spec:
      containers:
        - image: mainamctk33/reactjs:1.0
          imagePullPolicy: Always
          name: kios
          ports:
            - containerPort: 80
              name: 80tcp32000
              protocol: TCP
              _listeningPort: 32000
              _serviceType: NodePort
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: vol-knep7
          __active: true
          resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol-knep7
          nfs:
            path: /mnt/NFS_Share/project-react-js-smart-kios/app
            server: 10.0.0.18
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
__clone: true
